"""Initial migration based on models

Revision ID: 385d8042251e
Revises: 
Create Date: 2025-03-30 14:27:33.465479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385d8042251e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_categories_id'), 'exercise_categories', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_categories_name'), 'exercise_categories', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.Enum('WORKOUT_CREATION', 'DIET_RECOMMENDATION', 'FITNESS_ADVICE', 'PROGRESS_ANALYSIS', name='aioperationtype'), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_tracking_operation_type', 'ai_tracking', ['operation_type'], unique=False)
    op.create_index('idx_ai_tracking_user_id', 'ai_tracking', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_tracking_id'), 'ai_tracking', ['id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('muscle_groups', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('form_tips', sa.Text(), nullable=True),
    sa.Column('common_mistakes', sa.Text(), nullable=True),
    sa.Column('variations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['exercise_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_exercise_id'), 'exercises', ['exercise_id'], unique=True)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('TOKEN_REQUEST', 'TOKEN_APPROVED', 'TOKEN_REJECTED', 'WORKOUT_COMPLETED', 'NEW_EXERCISE', 'ADMIN_NOTIFICATION', 'SYSTEM_NOTIFICATION', name='notificationtype'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('token_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='tokenrequeststatus'), nullable=True),
    sa.Column('request_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_requests_id'), 'token_requests', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('fitness_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='fitnesslevel'), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'EXTREMELY_ACTIVE', name='activitylevel'), nullable=True),
    sa.Column('weight_goal_kg', sa.Float(), nullable=True),
    sa.Column('weekly_workout_goal', sa.Integer(), nullable=True),
    sa.Column('preferred_workout_duration', sa.Integer(), nullable=True),
    sa.Column('preferred_workout_days', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('favorite_muscle_groups', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('has_injuries', sa.Boolean(), nullable=True),
    sa.Column('injury_notes', sa.String(), nullable=True),
    sa.Column('has_medical_conditions', sa.Boolean(), nullable=True),
    sa.Column('medical_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_profile_user_id', 'user_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    op.create_index(op.f('ix_workouts_title'), 'workouts', ['title'], unique=False)
    op.create_table('scheduled_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_workouts_id'), 'scheduled_workouts', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_title'), 'scheduled_workouts', ['title'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rest_time_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercises_id'), 'workout_exercises', ['id'], unique=False)
    op.create_table('workout_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date_completed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_histories_id'), 'workout_histories', ['id'], unique=False)
    op.create_index(op.f('ix_workout_histories_title'), 'workout_histories', ['title'], unique=False)
    op.create_table('scheduled_workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rest_time_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['scheduled_workout_id'], ['scheduled_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_workout_exercises_id'), 'scheduled_workout_exercises', ['id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('EARN', 'SPEND', 'ADMIN_ADJUSTMENT', name='tokentransactiontype'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('workout_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['token_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_history_id'], ['workout_histories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_table('workout_exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rest_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercise_sets_id'), 'workout_exercise_sets', ['id'], unique=False)
    op.create_table('workout_history_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_history_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_history_id'], ['workout_histories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_history_exercises_id'), 'workout_history_exercises', ['id'], unique=False)
    op.create_table('scheduled_workout_exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_workout_exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rest_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_workout_exercise_id'], ['scheduled_workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_workout_exercise_sets_id'), 'scheduled_workout_exercise_sets', ['id'], unique=False)
    op.create_table('workout_history_exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_history_exercise_id', sa.Integer(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('planned_reps', sa.Integer(), nullable=True),
    sa.Column('planned_weight', sa.Float(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('rest_time_seconds', sa.Integer(), nullable=True),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_history_exercise_id'], ['workout_history_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_history_exercise_sets_id'), 'workout_history_exercise_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_history_exercise_sets_id'), table_name='workout_history_exercise_sets')
    op.drop_table('workout_history_exercise_sets')
    op.drop_index(op.f('ix_scheduled_workout_exercise_sets_id'), table_name='scheduled_workout_exercise_sets')
    op.drop_table('scheduled_workout_exercise_sets')
    op.drop_index(op.f('ix_workout_history_exercises_id'), table_name='workout_history_exercises')
    op.drop_table('workout_history_exercises')
    op.drop_index(op.f('ix_workout_exercise_sets_id'), table_name='workout_exercise_sets')
    op.drop_table('workout_exercise_sets')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_scheduled_workout_exercises_id'), table_name='scheduled_workout_exercises')
    op.drop_table('scheduled_workout_exercises')
    op.drop_index(op.f('ix_workout_histories_title'), table_name='workout_histories')
    op.drop_index(op.f('ix_workout_histories_id'), table_name='workout_histories')
    op.drop_table('workout_histories')
    op.drop_index(op.f('ix_workout_exercises_id'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_scheduled_workouts_title'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_id'), table_name='scheduled_workouts')
    op.drop_table('scheduled_workouts')
    op.drop_index(op.f('ix_workouts_title'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index('idx_user_profile_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_token_requests_id'), table_name='token_requests')
    op.drop_table('token_requests')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notification_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exercise_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_ai_tracking_id'), table_name='ai_tracking')
    op.drop_index('idx_ai_tracking_user_id', table_name='ai_tracking')
    op.drop_index('idx_ai_tracking_operation_type', table_name='ai_tracking')
    op.drop_table('ai_tracking')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exercise_categories_name'), table_name='exercise_categories')
    op.drop_index(op.f('ix_exercise_categories_id'), table_name='exercise_categories')
    op.drop_table('exercise_categories')
    # ### end Alembic commands ### 